[extra.ford]
project_url = "crisbh.github.io/gramses/"
exclude_dir = ["docs","doc","namelist","bin"]
src_dir = ["amr","aton","hydro","mhd","pario","patch","pm","poisson","rhd","rt","utils"]
output_dir = "docs/_site"
graph = true
search = false
preprocess = true
macro = ["USE_MPI","DIM=3"]
extensions = ["f90","f95","F90","F95"]
md_extensions = ["markdown.extensions.tables","markdown.extensions.fenced_code","markdown.extensions.toc"]

