[extra.ford]
project = "GRAMSES"
summary = "Numerical relativity N-body simulations in cosmology based on RAMSES"
author = "Cristian Barrera-Hinojosa and Baojiu Li. RAMSES has been developed by R. Teyssier"
src_dir = ["amr","aton","hydro","pario","pm","poisson","utils"]
exclude_dir = ["docs","doc","namelist","bin", "patch", "rhd", "rt", "mhd"]
output_dir = "docs/_site"
graph = true
search = false
preprocess = true
macro = ["USE_MPI","DIM=3"]
extensions = ["f90","f95","F90","F95"]
md_extensions = ["markdown.extensions.tables","markdown.extensions.fenced_code","markdown.extensions.toc"]

